myStr = "Python String"
print(myStr)
print(myStr [0])
print(myStr [3:8])
print(myStr [4:])
print(myStr [:5])
print(myStr [:5:2])
print(myStr * 3)
print(myStr + " is powerfull.")
print(myStr, "is powerfull.")
print(myStr, "is powerfull",sep=';')
print('n' in myStr)
print('j' not in myStr)
print("Here is my display %s"% "Python is powerfull")
print("Here is my display \t%s"% myStr)
print("Here is my display %s"% myStr)
