import math
mytup= (0,'good','soccer',35.1,'player',8)
mytup2=(4,5,0,9)
mytup3=(99,)
#mytup3[0] = (100)
print(mytup3)
print(mytup[1:3])
print(mytup2[2:])
print(len(mytup))
print(mytup + mytup2)
print(mytup * 3)
print('good' in mytup)
print(max(mytup2))
print(min(mytup2))
print(sorted(mytup2))
d=(mytup2==mytup3)
print(d)
print(mytup2==mytup3)
