myList = ["Hi", "This", "is", "my", "first", "Python", "program"]
subList = [1,2,3,4,5]
print("1. Checking length of myList...")
print("Length of myList : ",len(myList))
print("\n2. Checking length of subList...")
print("Length of subList : ",len(subList))
print("\n3. Appending an object 'Thanks' in myList...")
myList.append("Thanks")
print("Appended list : ", myList)
print("\n4. Counting number of times the word 'is' exists in myList")
print("Count of word 'is' in myList : ",myList.count("is"))
print("\n5. Exteding myList...")
myList.extend(subList)
print("Extended myList : ",myList)
print("\n6. Finding the index of any object in myList...")
print("Index of word 'first' in myList : ",myList.index("first"))
print("\n7. Insert object 'duplicate' at index 3")
myList.insert(3,"duplicate")
print("Updated myList : ",myList)
print("\n8. Popping the last object form myList...")
print("Popped object : ",myList.pop())
print("Updated list : ",myList)
print("\n9. Popping an object from index 2...")
print("Popped object : ",myList.pop(2))
print("Updated list : ",myList)
print("\n10. Removing the object 'duplicate' from myList")
myList.remove("duplicate")
print("Updated list : ",myList)
print("\n11. Reversing the order of myList...")
print(myList.reverse())
print("Reversed list : ",myList)
